basePath: /
definitions:
  models.Event:
    properties:
      description:
        description: Description de l'événement
        type: string
      end:
        description: Heure de fin (chaîne pour compatibilité)
        type: string
      id:
        description: Identifiant unique généré localement
        type: string
      location:
        description: Lieu de l'événement
        type: string
      name:
        description: Nom de l'événement
        type: string
      resources:
        description: ID des ressource associée
        items:
          type: integer
        type: array
      start:
        description: Heure de début
        type: string
      uid:
        description: UID de l'événement
        type: string
      updated_at:
        description: Dernière mise à jour
        type: string
    type: object
info:
  contact:
    email: beldjilaliyanis@gmail.com, cerrafr31@gmail.com
    name: Yanis BELDJILALI, Adel CERRA
  description: API to manage events in the timetable.
  title: timetable API
  version: 1.0.0
paths:
  /events:
    get:
      consumes:
      - application/json
      description: Fetches all events from the database, or filter events by the provided
        resource ID if specified.
      parameters:
      - description: Resource ID
        in: query
        name: resourceId
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Event'
            type: array
        "400":
          description: Invalid resource ID format
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get all events or filter by resource ID
      tags:
      - events
  /events/{eventId}:
    get:
      consumes:
      - application/json
      description: Retrieves an event by its unique ID from the database
      parameters:
      - description: Event ID
        in: path
        name: eventId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Event'
        "400":
          description: Invalid Event ID
          schema:
            type: string
        "404":
          description: Event not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get event by ID
      tags:
      - events
schemes:
- http
swagger: "2.0"
